# This workflow will build a package using Maven and then publish it to OSS Sonatype Maven repository when a release is created
# It can also be reused by other workflows to publish artifacts from other repositories (usually within the Hevelian organization).
name: Maven Deploy

on:
  release:
    types: [created]
  workflow_dispatch:
  #To be able to reuse this workflow in similar projects.
  # This is a first simplified version, that will do the job just fine.
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
    secrets:
      OSSRH_USERNAME:
        required: true
      OSSRH_TOKEN:
        required: true
      MAVEN_GPG_PRIVATE_KEY:
        required: true
      MAVEN_GPG_PASSPHRASE:
        required: true

env:
  # Java version required to build this project in case the workflow is triggered within the current repo.
  BUILD_TOOLS_JAVA_VERSION: '11'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ inputs.java-version || env.BUILD_TOOLS_JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version || env.BUILD_TOOLS_JAVA_VERSION }}
        distribution: temurin
        cache: maven
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_TOKEN
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Build and Deploy with Maven
      run: mvn clean deploy -Prelease
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
